#!/bin/bash
Fail()
{
    echo "FATAL($0): $1"
    exit 1
}

g++ -Wall -Werror -O3 -o endgame endgame.cpp board.cpp main.cpp || Fail "Error building C++ code."
./endgame test || Fail "Failed unit tests."
for db in q bn; do
    ./endgame generate ${db} || Fail "Error generating database ${db}"
done
exit 0
