#!/bin/bash
Fail()
{
    echo "FATAL($0): $1"
    exit 1
}

g++ -o endgame endgame.cpp board.cpp main.cpp || Fail "Error building C++ code."
./endgame test || Fail "Failed unit tests."
./endgame generate q
exit 0
